# Generated by Django 3.2.3 on 2021-05-26 16:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_cellar_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingCellar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[['0-2', '0-2'], ['2-4', '2-4'], ['6-8', '6-8'], ['10-12', '10-12'], ['14-16', '14-16'], ['XS', 'XS'], ['S', 'S'], ['M', 'M'], ['L', 'L'], ['XL', 'XL'], ['XXL', 'XXL'], ['XXXL', 'XXXL']], default='NONE', max_length=20)),
                ('color', models.CharField(choices=[['#7D7D7D', 'ROJO'], ['#D7DDF5', 'AZUL OSCURO'], ['#7D7D7D', 'BLANCO'], ['#7D7D7D', 'GRIS'], ['#7D7D7D', 'LILA'], ['#D6D3CC', 'HUESO']], default='#7D7D7D', max_length=10)),
                ('state', models.CharField(choices=[['OK', 'PRODUCTO OK'], ['DEFECTIVE', 'PRODUCTO DEFECTUOSO'], ['DAMAGED', 'PRODUCTO DAÑADO']], default='OK', max_length=20)),
                ('info', models.TextField(default='OK')),
                ('product_cellar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_cellar_app.productcellar')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
