# Generated by Django 3.2.3 on 2021-05-27 21:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection_app', '0001_initial'),
        ('section_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(default='CELL-PROD-###-####', max_length=20)),
                ('name', models.CharField(default='NOT INCLUDED', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('utility', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('discount', models.IntegerField(default=0)),
                ('discount_unit', models.IntegerField(default=0)),
                ('description', models.TextField(default='NOT INCLUDED')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection_app.collection')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='section_app.section')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
