# Generated by Django 3.2.3 on 2021-05-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_sale_app', '0002_auto_20210527_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='utility',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
