# Generated by Django 3.2.3 on 2021-05-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellar',
            name='short_name',
            field=models.CharField(default='CELLAR', max_length=6, null=True),
        ),
    ]
