# Generated by Django 3.2.3 on 2021-05-28 03:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_type', models.CharField(choices=[['C.C.', 'CEDULA DE CIUDADANIA'], ['C.E.', 'CEDULA DE EXTRANJERIA'], ['N.I.P.', 'NUMERO DE IDENTIFICACION PERSONAL'], ['N.I.T.', 'NUMERO DE IDENTIFICACION TRIBUTARIA'], ['T.I.', 'TARJETA DE IDENTIDAD'], ['P.A.P.', 'PASAPORTE']], default='NOT INCLUDED', max_length=15)),
                ('id', models.CharField(default='NOT INCLUDED', max_length=20)),
                ('name', models.CharField(default='NOT INCLUDED', max_length=80)),
                ('last_name', models.CharField(default='NOT INCLUDED', max_length=80)),
                ('address', models.CharField(default='NOT INCLUDED', max_length=80)),
                ('phone_number', models.CharField(default='NOT INCLUDED', max_length=12)),
                ('email', models.EmailField(default='notIncluded@marca.com', max_length=254)),
                ('gender', models.CharField(choices=[['M', 'MASCULINO'], ['F', 'FEMENINO'], ['I', 'NO DEFINIDO'], ['N', 'NO SUMINISTRADO']], default='I', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
