# Generated by Django 3.2.3 on 2021-05-25 16:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cellar_app', '0001_initial'),
        ('provider_app', '0002_alter_provider_identification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCellar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(default='PROD-C-', max_length=20)),
                ('name', models.CharField(default='NOT INCLUDED', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('quantity_entered', models.PositiveIntegerField(default=0)),
                ('free_quantity', models.PositiveIntegerField(default=0)),
                ('stop', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(default='NOT INCLUDED')),
                ('cellar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cellar_app.cellar')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provider_app.provider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
