# Generated by Django 3.2.3 on 2021-05-28 00:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_cellar_app', '0001_initial'),
        ('product_sale_app', '0003_auto_20210527_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCellarSale',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product_cellar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_cellar_app.productcellar')),
                ('product_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_sale_app.productsale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
