# Generated by Django 3.2.3 on 2021-05-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_cellar_sale_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcellarsale',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
